// frontend/apps/svelte/src/views/HomeView.svelte
<script lang="ts">
  import { push } from 'svelte-spa-router'
  import ListTabs from '../components/ListTabs.svelte'
  import BookSearch from '../components/BookSearch.svelte'
  import BookList from '../components/BookList.svelte'
  import BookDashboard from '../components/BookDashboard.svelte'
  import FriendRecommendationsCarousel from '../components/FriendRecommendationsCarousel.svelte'
  import { activeTab } from '../stores/books'
  import { logout, user, isAuthenticated } from '../stores/auth'

  function handleLogout() {
    logout()
    push('/')
  }
</script>

<main class="app">
  <header class="app-header">
    <div>
      <h1>Mybooks</h1>
      <p>Gestiona tus listas de libros</p>
    </div>

    {#if $user}
      <div class="user-bar">
        <button
          type="button"
          class="user-name"
          onclick={() => push(`/users/${$user.id}`)}
        >
          {$user.name}
        </button>
        <button type="button" class="btn-secondary" onclick={handleLogout}>
          Cerrar sesión
        </button>
      </div>
    {:else}
      <div class="user-bar">
        <button type="button" class="btn-secondary" onclick={() => push('/login')}>
          Iniciar sesión
        </button>
        <button type="button" class="btn-primary-link" onclick={() => push('/register')}>
          Registrarse
        </button>
      </div>
    {/if}
  </header>

  <div class="layout">
    <aside class="sidebar">
      <ListTabs />
      {#if $isAuthenticated}
        <FriendRecommendationsCarousel />
      {/if}
    </aside>

    <section class="search-panel">
      <BookSearch />
    </section>
  </div>

  <section class="list-panel">
    {#if $activeTab === 'dashboard'}
      <BookDashboard />
    {:else}
      <BookList />
    {/if}
  </section>
</main>

<style>
  .app-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 1rem;
    flex-wrap: wrap;
    margin-bottom: 1.5rem;
  }

  .user-bar {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .user-name {
    color: var(--muted);
    font-size: 0.95rem;
    padding: 0;
    border: none;
    background: none;
    cursor: pointer;
    text-decoration: underline;
  }

  .user-name:hover {
    color: var(--primary);
  }
</style>

// frontend/apps/vue/src/views/HomeView.vue
<script setup lang="ts">
import { useRouter } from 'vue-router'
import ListTabs from '../components/ListTabs.vue'
import FriendRecommendationsCarousel from '../components/FriendRecommendationsCarousel.vue'
import BookSearch from '../components/BookSearch.vue'
import BookList from '../components/BookList.vue'
import BookDashboard from '../components/BookDashboard.vue'
import { activeTab } from '../stores/books'
import { isAuthenticated, logout, user } from '../stores/auth'

const router = useRouter()

function handleLogout() {
  logout()
  router.push('/')
}
</script>

<template>
  <main class="app">
    <header class="app-header">
      <div>
        <h1>Mybooks</h1>
        <p>Gestiona tus listas de libros</p>
      </div>

      <div v-if="user" class="user-bar">
        <RouterLink :to="`/users/${user.id}`" class="user-name">
          {{ user.name }}
        </RouterLink>
        <button type="button" class="btn-secondary" @click="handleLogout">
          Cerrar sesión
        </button>
      </div>

      <div v-else class="user-bar">
        <button type="button" class="btn-secondary" @click="router.push('/login')">
          Iniciar sesión
        </button>
        <button type="button" class="btn-primary-link" @click="router.push('/register')">
          Registrarse
        </button>
      </div>
    </header>

    <div class="layout">
      <aside class="sidebar">
        <ListTabs />
        <FriendRecommendationsCarousel v-if="isAuthenticated" />
      </aside>

      <section class="search-panel">
        <BookSearch />
      </section>
    </div>

    <section class="list-panel">
      <BookDashboard v-if="activeTab === 'dashboard'" />
      <BookList v-else />
    </section>
  </main>
</template>

<style scoped>
.app-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 1rem;
  flex-wrap: wrap;
}

.user-bar {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.user-name {
  color: var(--muted);
  font-size: 0.95rem;
  text-decoration: none;
}

.user-name:hover {
  color: var(--primary);
}
</style>
